config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'
  get 'orders/show'
  get 'orders/new'
  get 'carts/show'
  devise_for :users
  resources :books
  #get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "books#index"

  get 'carts/:id' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"

  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"
  resources :orders

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Books', root_path, class:"nav-link" %>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <li class="nav-item">
            <%= link_to 'My Cart', cart_path(@current_cart), class:"nav-link" %>
        </li>
        <% if user_signed_in? %>
            <% if current_user.is_seller %>
                <li class="nav-item">
                    <%= link_to 'Create Book Listing', new_book_path, class:"nav-link" %>
                </li>
            <% end %>
            <li class="nav-item">
                <%= link_to 'Sign Out', destroy_user_session_path, method: :get, class:"nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to 'My Profile', edit_user_registration_path, class:"nav-link" %>
            </li>
            <% if current_user.is_seller %>
                <li class="nav-item">
                    <%= link_to 'My Sales', orders_path, class:"nav-link" %>
                </li>
            <% end %>
        <% else %>
            <li class="nav-item">
                <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %>
            </li>
        <% end %>
      </ul>
      <form class="d-flex">

        <%= simple_form_for :search, url: books_path, method: "GET", html: { class: 'form-control me-2', type: 'search', placeholder: 'search' } do |f| %>
        <%= f.input :title, label: false, input_html: {value: "", class: 'form-control'}, placeholder: 'search'  %>
        <%= f.submit "Search", class: "btn btn-outline-success" %>
        <% end %>
      </form>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<div class="container"> 
    <h1>Home#index</h1>
</div>
<p>Find me in app/views/home/index.html.erb</p>