config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'
  get 'orders/show'
  get 'orders/new'
  get 'carts/show'
  devise_for :users
  resources :books
  #get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "books#index"

  get 'carts/:id' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"

  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"
  resources :orders

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :line_items, dependent: :destroy
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /books or /books.json
  def index
    @books = Book.all
    @search = params["search"]
    if @search.present?
      @title = @search["title"]
      @books = Book.where("title ILIKE ?", "%#{@title}%")
    end
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    #@book = Book.new
    @book = current_user.books.build
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    #@book = Book.new(book_params)
    @book = current_user.books.build(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @book = current_user.books.find_by(id: params[:id])
    redirect_to books_path, notice: "Not authorized to edit this book." if @book.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:book_id, :title, :description, :author, :price, :stock, :available, :user_id)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div class="col" id="<%= dom_id book %>">
  <div class="card" style="width: 18rem;">
    <div class="card-header">
    <h4> <%= book.title %> </h4>
    </div>
    <%= image_tag("book.jpg", :alt => "book", :class => "card-img-top") %>
    <div class="card-body">
      <h5 class="card-title"> $<%= book.price %></h5>
      <p class="card-text"> Author: <%= book.author %></p>
      <%= link_to "Show this book", book, class:"btn btn-primary" %>
    </div>
  </div>
</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-label">
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="form-label">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description, class:"form-control" %>
  </div>

  <div class="form-label">
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author, class:"form-control" %>
  </div>

  <div class="form-label">
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price, class:"form-control" %>
  </div>

  <div class="form-label">
    <%= form.label :stock, style: "display: block" %>
    <%= form.number_field :stock, class:"form-control" %>
  </div>

  <div class="form-label">
    <%= form.label :available, style: "display: block" %>
    <%= form.check_box :available, checked: true, class:"form-check-input" %>
  </div>

  <div class="form-label">
    <%= form.text_field :user_id, class:"form-control", value: current_user.id, type: :hidden %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/index.html.erb
<h1>Books</h1>

<div id="books">
  <div class="row row-cols-1 row-cols-md-3 g-4">
    <% @books.each do |book| %>
      <%= render book %>
    <% end %>
  </div>
</div>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/show.html.erb
<div class="container-fluid">
  <div class="card mb-3">
    <%= image_tag("book.jpg", :alt => "book", :class => "card-img-top") %>
    <div class="card-body">
      <h5 class="card-title"><%= @book.title %> ($<%= @book.price%>)</h5>
      <p class="card-text"> Author: <%= @book.author %></p>
      <p class="card-text"> Description: <%= @book.description %></p>
      <p class="card-text"> Seller: <%= @book.user_id %></p>
      <p class="card-text"><small class="text-muted">In Stock: <%= @book.stock %></small></p>
      <% if @book.available == false%>
        <div class="alert alert-warning" role="alert">
          This book has been set as unavailable by the seller.
        </div>
      <% end %>
      <%= button_to "Add to cart", line_items_path(:book_id => @book.id), class:'btn btn-primary', :disabled => (@book.stock <= 0 or @book.available == false)%>
      <br>

      <% if user_signed_in? %>
        <% if @book.user_id == current_user.id %>
          <div class="btn-group" role="group">
            <%= link_to "Edit this book", edit_book_path(@book), class:'btn btn-secondary' %>
            <%= button_to "Remove this book from sale", @book, method: :delete, class:'btn btn-danger' %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<% 
=begin %>
<div>
  <%= link_to "Edit this book", edit_book_path(@book) %> |
  <%= link_to "Back to books", books_path %>
  <%= button_to "Add to cart", line_items_path(:book_id => @book.id)%>
  <%= button_to "Destroy this book", @book, method: :delete %>
</div>
<% 
=end %>