config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'
  get 'orders/show'
  get 'orders/new'
  get 'carts/show'
  devise_for :users
  resources :books
  #get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "books#index"

  get 'carts/:id' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"

  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"
  resources :orders

end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :books, through: :line_items

  # LOGIC
  def sub_total
    sum = 0
    self.line_items.each { |line_item| sum += line_item.total_price }
    return sum
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = @current_cart
  end

  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<h2>My Cart</h2>
<ul>
  <% @cart.line_items.each do |line_item| %>
    <li>Item: <%= line_item.book.title %>/ Price: <%= number_to_currency(line_item.book.price) %>/ Quantity: <%= line_item.quantity %>/ Total Price: <%= number_to_currency(line_item.total_price) %>
    <br>
    <div class="btn-toolbar" role="group" aria-label="Basic example">
        <%= button_to " + ", line_item_add_path(:id => line_item), method: :post, class:"btn btn-success mr-5" %>
        <%= button_to " - ", line_item_reduce_path(:id => line_item), method: :post, class:"btn btn-secondary mr-5" %>
        <%= button_to "Remove item", line_item_path(line_item), method: :delete, class:"btn btn-danger mr-5" %>
    </div>

  <% end %>
</ul>
<h3>Sub total: <%= number_to_currency(@cart.sub_total) %></h3>

<% puts "||||||||||||||||||||||||||||||" %>
<% if user_signed_in? %>
    <%= link_to_if (@cart.sub_total < current_user.balance), "Proceed to checkout", new_order_path, class:"btn btn-primary" %> <br>
<% else %>
    <%= link_to "Proceed to checkout", new_user_session_path, class:"btn btn-primary" %> <br>
<% end %>